package com.unibo.scalaparty.prolog

import com.unibo.scalaparty.core.geometry.Point2D
import com.unibo.scalaparty.core.map.SpawnPoint
import com.unibo.scalaparty.core.model.ArenaSettings
import org.scalatest.matchers.should.Matchers
import org.scalatest.wordspec.AnyWordSpec

class PrologGameMapProviderSpec extends AnyWordSpec with Matchers:

  private val provider = PrologGameMapProvider()
  private val supportedPlayers = 1 to 4

  private def providerAnswering(theory: String) = PrologGameMapProvider(PrologEngine(theory))

  "A PrologGameMapProvider" should:

    "provide a map hosting exactly the requested players" in:
      supportedPlayers.foreach: players =>
        provider.mapFor(players).map(_.capacity) shouldBe Some(players)

    "translate the map generated by the theory" in:
      val map = provider.mapFor(2).get
      map.arena shouldBe ArenaSettings(800, 800)
      map.playerSpawns shouldBe List(SpawnPoint(Point2D(202, 202), 45.0), SpawnPoint(Point2D(598, 598), 225.0))

    "provide no map when the theory generates none" in:
      provider.mapFor(supportedPlayers.max + 1) shouldBe None

    "reject a request for a non-positive number of players" in:
      List(0, -1).foreach: players =>
        an[IllegalArgumentException] should be thrownBy provider.mapFor(players)

    "fail when the theory answers with a malformed map" in:
      val malformedTheories = List(
        "game_map(_, not_a_map).",
        "game_map(_, game_map(arena(800, 800), [not_a_spawn]))."
      )
      malformedTheories.foreach: theory =>
        an[IllegalStateException] should be thrownBy providerAnswering(theory).mapFor(1)
