package com.unibo.scalaparty.core.engine

import com.unibo.scalaparty.core.dto.{toDto, EntityDto}
import com.unibo.scalaparty.core.ecs.*
import com.unibo.scalaparty.core.ecs.systems.*
import com.unibo.scalaparty.core.engine.input.InputGateway
import com.unibo.scalaparty.core.geometry.Shape
import com.unibo.scalaparty.core.model.GameCommand

/** A trait representing the game engine responsible for updating the state of the game world based on player commands and elapsed time. */
trait GameEngine:
  /** Returns the bounding box of the game arena. */
  def arena: Shape.AABB

  /** Updates the state of the game world based on the provided player commands and the elapsed time.
   *
   *  @param commands  a list of player commands to be processed
   *  @param dt    the elapsed time since the last update, in milliseconds
   *  @return a new list of entities representing the updated state of the game world
   */
  def update(commands: List[GameCommand], dt: Long): List[EntityDto]

object GameEngine:
  /** Creates a new instance of the game engine based on the provided game configuration.
   *
   *  @param config the game configuration
   *  @return a new instance of GameEngine
   */
  def apply(config: GameConfig): GameEngine =
    GameEngine(config, WorldSystem.defaultPipeline(config.settings))

  /** Creates a new instance of the game engine based on the provided game configuration and system pipeline.
   *
   *  @param config   the game configuration
   *  @param pipeline the system pipeline to be used for updating the game world
   *  @return a new instance of GameEngine
   */
  def apply(config: GameConfig, pipeline: WorldSystem): GameEngine =
    new DefaultGameEngine(config, pipeline)

private class DefaultGameEngine(config: GameConfig, pipeline: WorldSystem) extends GameEngine:
  private var world: GameWorld = config.map.buildWorld(config.settings)(config.players)
  val arena: Shape.AABB = config.map.shape

  override def update(commands: List[GameCommand], dt: Long): List[EntityDto] =
    // We're throwing away the events generated by the systems, but this is just because in the current implementation we don't need them.
    // Serializing them would be a waste of resources
    val (nextWorld, _) = InputGateway
      .processCommands(this.world, commands)
      .computeNext(pipeline, dt)
    world = nextWorld
    world.serialized

extension (world: GameWorld)

  /** Converts the entities in the game world to their corresponding DTO representations.
   *
   *  @return a list of EntityDto representing the entities in the game world
   */
  private def serialized: List[EntityDto] = world.entitiesWithComponents
    .map(_.toDto)
    .collect:
      case Some(dto) => dto

  /** Computes the next state of the game world by applying the provided system pipeline and elapsed time.
   * 
   * @param pipeline the system pipeline to be applied to the game world
   * @param dt the elapsed time since the last update, in milliseconds
   * @return a tuple containing the updated game world and a set of new game events generated during the update
   */
  private def computeNext(pipeline: WorldSystem, dt: Long): SystemOutput = pipeline.update(world, Set.empty, dt)
