package com.unibo.scalaparty.core.ecs.systems

import com.unibo.scalaparty.core.ecs.{Component, EntityId, GameEvent, GameWorld}
import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers

class WorldSystemSpec extends AnyFlatSpec with Matchers:

  private val testEntityId = EntityId.generate()
  private val defaultDt = 16L
  private val initialWorld = GameWorld.empty

  private case class EmptyComponent() extends Component

  "A composed WorldSystem" should "execute systems sequentially and pass the updated state forward" in:
    // Spawner system adds an entity
    val spawnerSystem: WorldSystem = (world, events, _) =>
      val nextWorld = world.addEntity(testEntityId, List(EmptyComponent()))
      (nextWorld, events)
    // Destroyer system expects the entity to exist and removes it
    val destroyerSystem: WorldSystem = (world, events, _) =>
      val nextWorld = world.removeEntity(testEntityId)
      (nextWorld, events)
    val pipeline = spawnerSystem >> destroyerSystem
    val (finalWorld, _) = pipeline.update(initialWorld, Set.empty, defaultDt)
    finalWorld.findComponents(testEntityId) shouldBe empty

  it should "aggregate the events generated by all the systems in the pipeline" in:
    val eventA = GameEvent.Death(EntityId.generate())
    val eventB = GameEvent.Death(EntityId.generate())
    // System A generates eventA
    val systemA: WorldSystem = (world, events, _) => (world, events + eventA)
    // System B generates eventB
    val systemB: WorldSystem = (world, events, _) => (world, events + eventB)
    val pipeline = systemA >> systemB
    val (_, finalEvents) = pipeline.update(initialWorld, Set.empty, defaultDt)
    // The resulting set must contain both events generated by the pipeline
    finalEvents should contain allOf (eventA, eventB)
